// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/enterprise": {
    params: {};
  };
  "/courses": {
    params: {};
  };
  "/extensions/architecture-and-advanced-patterns": {
    params: {};
  };
  "/extensions/advanced-concepts": {
    params: {};
  };
  "/extensions/authentication-and-authorization": {
    params: {};
  };
  "/extensions/microservices": {
    params: {};
  };
  "/extensions/graphql-code-first": {
    params: {};
  };
  "/extensions/graphql-schema-first": {
    params: {};
  };
  "/extensions/graphql-bundle": {
    params: {};
  };
  "/extensions/advanced-bundle": {
    params: {};
  };
  "/extensions/all-in-one-bundle": {
    params: {};
  };
  "/extensions/extensions-bundle": {
    params: {};
  };
  "/jobs": {
    params: {};
  };
  "/tools/mau": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/enterprise" | "/courses" | "/extensions/architecture-and-advanced-patterns" | "/extensions/advanced-concepts" | "/extensions/authentication-and-authorization" | "/extensions/microservices" | "/extensions/graphql-code-first" | "/extensions/graphql-schema-first" | "/extensions/graphql-bundle" | "/extensions/advanced-bundle" | "/extensions/all-in-one-bundle" | "/extensions/extensions-bundle" | "/jobs" | "/tools/mau";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/enterprise.tsx": {
    id: "routes/enterprise";
    page: "/enterprise";
  };
  "routes/courses.tsx": {
    id: "routes/courses";
    page: "/courses";
  };
  "routes/extensions/architecture-and-advanced-patterns.tsx": {
    id: "routes/extensions/architecture-and-advanced-patterns";
    page: "/extensions/architecture-and-advanced-patterns";
  };
  "routes/extensions/advanced-concepts.tsx": {
    id: "routes/extensions/advanced-concepts";
    page: "/extensions/advanced-concepts";
  };
  "routes/extensions/authentication-and-authorization.tsx": {
    id: "routes/extensions/authentication-and-authorization";
    page: "/extensions/authentication-and-authorization";
  };
  "routes/extensions/microservices.tsx": {
    id: "routes/extensions/microservices";
    page: "/extensions/microservices";
  };
  "routes/extensions/graphql-code-first.tsx": {
    id: "routes/extensions/graphql-code-first";
    page: "/extensions/graphql-code-first";
  };
  "routes/extensions/graphql-schema-first.tsx": {
    id: "routes/extensions/graphql-schema-first";
    page: "/extensions/graphql-schema-first";
  };
  "routes/extensions/graphql-bundle.tsx": {
    id: "routes/extensions/graphql-bundle";
    page: "/extensions/graphql-bundle";
  };
  "routes/extensions/advanced-bundle.tsx": {
    id: "routes/extensions/advanced-bundle";
    page: "/extensions/advanced-bundle";
  };
  "routes/extensions/all-in-one-bundle.tsx": {
    id: "routes/extensions/all-in-one-bundle";
    page: "/extensions/all-in-one-bundle";
  };
  "routes/extensions/extensions-bundle.tsx": {
    id: "routes/extensions/extensions-bundle";
    page: "/extensions/extensions-bundle";
  };
  "routes/jobs.tsx": {
    id: "routes/jobs";
    page: "/jobs";
  };
  "routes/tools-mau.tsx": {
    id: "routes/tools-mau";
    page: "/tools/mau";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/enterprise": typeof import("./app/routes/enterprise.tsx");
  "routes/courses": typeof import("./app/routes/courses.tsx");
  "routes/extensions/architecture-and-advanced-patterns": typeof import("./app/routes/extensions/architecture-and-advanced-patterns.tsx");
  "routes/extensions/advanced-concepts": typeof import("./app/routes/extensions/advanced-concepts.tsx");
  "routes/extensions/authentication-and-authorization": typeof import("./app/routes/extensions/authentication-and-authorization.tsx");
  "routes/extensions/microservices": typeof import("./app/routes/extensions/microservices.tsx");
  "routes/extensions/graphql-code-first": typeof import("./app/routes/extensions/graphql-code-first.tsx");
  "routes/extensions/graphql-schema-first": typeof import("./app/routes/extensions/graphql-schema-first.tsx");
  "routes/extensions/graphql-bundle": typeof import("./app/routes/extensions/graphql-bundle.tsx");
  "routes/extensions/advanced-bundle": typeof import("./app/routes/extensions/advanced-bundle.tsx");
  "routes/extensions/all-in-one-bundle": typeof import("./app/routes/extensions/all-in-one-bundle.tsx");
  "routes/extensions/extensions-bundle": typeof import("./app/routes/extensions/extensions-bundle.tsx");
  "routes/jobs": typeof import("./app/routes/jobs.tsx");
  "routes/tools-mau": typeof import("./app/routes/tools-mau.tsx");
};