// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/enterprise": {
    params: {};
  };
  "/courses": {
    params: {};
  };
  "/tools/mau": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/enterprise" | "/courses" | "/tools/mau";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/enterprise.tsx": {
    id: "routes/enterprise";
    page: "/enterprise";
  };
  "routes/courses.tsx": {
    id: "routes/courses";
    page: "/courses";
  };
  "routes/tools-mau.tsx": {
    id: "routes/tools-mau";
    page: "/tools/mau";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/enterprise": typeof import("./app/routes/enterprise.tsx");
  "routes/courses": typeof import("./app/routes/courses.tsx");
  "routes/tools-mau": typeof import("./app/routes/tools-mau.tsx");
};